### ISSUE TITLE
Unicode names displayed wrong

### ISSUE THREAD

**Issue by ozanbdesign** [watsonbox/exportify#145]
great project thank you

my issue is when i export csv

unicode names in filename.csv are right 

however inside csv file, song filenames are wrong and replaced by other characters

for example in spanish for ñ or similar characters

**Comment by Hydramus** [comment]
Hi yeah I have the same problem with all non-latin characters i.e. Chinese or Japanese with this. 

Is there anyway around this?

**Comment by Huang2326** [comment]
> Hi yeah I have the same problem with all non-latin characters i.e. Chinese or Japanese with this.
> 
> Is there anyway around this?

I found an way to solve it.(My eng is unskillful,maybe has some mistake on expression)
use notepad open the csv file,you can see Encoding format which the csv file use (In the bottom right corner and Maybe it's utf8)
close the notepad ,open the csv files by Excel(do not use WPS because I haven't tried before).
found data-‘get Data’-'from file'-'from text/csv'
choose your csv file
an it will open an new page, choose"65001:unicode(UTF-8)"
and you can see it show correct word (the chinese and japanese are correct show in my computer and may spanish can work too)
push "load" and the correct list will save to your CSV file

**Comment by JimZhu6** [comment]
Thanks to @Huang2326 for the inspiration, in fact, you can directly import data in a new Excel file, just select utf8 encoding.
Here is an operation process, I hope it can help you.
![demo](https://github.com/watsonbox/exportify/assets/34890562/6789a346-03cd-471d-a5cc-be485a11e593)
