### ISSUE TITLE
Remove starred tracks feature as it no longer works

### ISSUE THREAD

**Issue by Nixtren** [watsonbox/exportify#16]
I can't seem to export starred tracks, it says "0 tracks". What's the current status on this?

**Comment by rain0r** [comment]
Can confirm this.

**Comment by watsonbox** [comment]
Hmm exporting starred tracks should work. It certainly works for me.

**Comment by ocram** [comment]
Starred tracks may first have been turned into a normal playlist called “Starred” and then phased out completely. But they may still be available. There’s no official information on that and a complete removal will not be announced in advance.

Anyway, since 2014, and for all new users anyway, the feature has been replaced with “Your music”. Support for that collection may be added as well: https://github.com/watsonbox/exportify/pull/37

**Comment by watsonbox** [comment]
Thanks for the info. It seems that we should phase out the feature since it isn't useful any more 👍 .

**Comment by watsonbox** [comment]
Fixed by https://github.com/watsonbox/exportify/commit/4cba84759294afb11ff3951fb3fa8ab5f2ec8358 and replaced by https://github.com/watsonbox/exportify/commit/bc5253c7ad0687eaaaad4cb761d9a836dbcbed83.
