### ISSUE TITLE
Allow playlists to be more easily searched or paged

### ISSUE THREAD

**Issue by jaalto** [watsonbox/exportify#19]
For my account, the opening page reads:

 Exportify: 1-20 of 2495 playlists for USERNAME

Now, scrolling through/between my lists by every 20th listing is impossible, 

Kindly provide dropown box to select E.g. 10, 20, 50, 100, 200, 400, ALL

**Comment by pavelkomarov** [comment]
How on earth do you have 2500 playlists? The reason it's 20 is that that's the max number you can get from Spotify at once, just like you can get no more than 50 artists in a single query, or no more than 100 songs.

**Comment by jaalto** [comment]
I simply do. This has to do with some freetime DJ work which needs aall kinds of playlist categorized by artist, genre, year, type of music, themes etc. They are all organized in folders etc. for easy access.

In that case, please document the limitation of the program e.g in the README

**Comment by jaalto** [comment]
Hm, I only would like to export the important playlsts. Could the program be extended to:

1. Query all playlists and save then to disk? (don't care how long it takes; might as well run 24h on otw idle computer)
2. Offer a FIELD where you can type in the EXACT NAME of playlist to get that exported?

**Comment by pavelkomarov** [comment]
[It can absolutely be modified to get *all* your playlists](https://github.com/pavelkomarov/exportify/issues/9). My version doesn't have the rate-limiting issues of this one, but I'm currently not querying for *all* playlists, only fetching the ones I already conveniently have listed on that page. If it really matters to you, comment over there.

It wouldn't take 24 hours to run, but it would be a while. It almost definitely wouldn't work totally flawlessly, because we've found there are some playlists that [cause odd unpredictable problems](https://github.com/pavelkomarov/exportify/issues/10). I'm catching those cases so I can tell the user and keep the thing from crashing, but those playlists don't end up in the final zip.

[live version](https://pavelkomarov.com/exportify/app)

**Comment by pavelkomarov** [comment]
It also could be modified to make the table sortable/searchable, but I'm not skilled enough at React yet to do it. 

https://github.com/pavelkomarov/exportify/issues/11
https://github.com/watsonbox/exportify/issues/62

**Comment by watsonbox** [comment]
Yes this is an interesting one, and it's not just presentational because it's quite important to be able to easily choose a playlist that you'd like to export 👍 . I think either a search or indeed modifiable page size would help with this, though I have a preference for a search to help with solving this specific use case.

The related but separate issue of rate limiting is here: https://github.com/watsonbox/exportify/issues/6.

**Comment by watsonbox** [comment]
I fixed this by implementing searching in https://github.com/watsonbox/exportify/pull/82
