### ISSUE TITLE
How can I add Release_date or release_date_ precision ?

### ISSUE THREAD

**Issue by Pancho111** [watsonbox/exportify#21]
Hi,
How can I add Release_date or release_date_ precision ?
I am trying to add it and no matter what,  I get Underfined.

thanks

**Comment by jonascj** [comment]
The reason why this it dose not work to do `item.track.album.release_date` is undefined is because the album object included with the tracks are a simplified album object: 
https://developer.spotify.com/web-api/get-track/  
https://developer.spotify.com/web-api/object-model/#album-object-simplified

To get at the release_date and release_date_precision you will need to `get-album` by its ID from the simplified album object `item.track.album.id` or `item.track.album.href`. That is one new query for each track to get its release date.

I'm not at all proficient in JS so I'm off to do this in python or similar.

**Comment by jhil** [comment]
@Pancho111 @jonascj - Did either of you end up working on this? I'm interested in getting data about albums in a playlist too. Might take a stab at it myself!

**Comment by jonascj** [comment]
@jhil yeah, but I decided not to modify the exportify code, I grew frustrated by my lack of javascript skills. So I just made something from scratch in python with the library `spotipy`. 

It shows the double query needed to get album date for each track:

https://github.com/jonascj/export-spotify-playlist-py

**Comment by jhil** [comment]
@jonascj - Awesome! Poking around your repo now :)

**Comment by jonascj** [comment]
@jhil It's not much, only one file to poke in! It would be nice if you ported it to exportify. It should be an extra option though because it impacts performance a great deal (one extra http query for each playlist item).
