### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by AmbieFm** [watsonbox/exportify#43]
Is this program still running, cannot get past the 'Get Started' feature anymore

**Comment by sokifree** [comment]
Same here, the error I get when clicking get started is

> exportify.js:172 Uncaught TypeError: Cannot read property 'uri' of null
>     at Constructor.render (<anonymous>:172:88)
>     at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (react.js:6975)
>     at ReactCompositeComponentWrapper._renderValidatedComponent (react.js:7002)
>     at ReactCompositeComponentWrapper.wrapper [as _renderValidatedComponent] (react.js:13427)
>     at ReactCompositeComponentWrapper.mountComponent (react.js:6423)
>     at ReactCompositeComponentWrapper.wrapper [as mountComponent] (react.js:13427)
>     at Object.mountComponent (react.js:14128)
>     at ReactDOMComponent.mountChildren (react.js:12871)
>     at ReactDOMComponent._createContentMarkup (react.js:7737)
>     at ReactDOMComponent.mountComponent (react.js:7647)

**Comment by martenjacobs** [comment]
I created a pull request that fixes this in #44

**Comment by shape55** [comment]
Thanks for this. However, I can't get past the first page. It loads & displays all the playlists (440 total) fine but when I hit "Export All" nothing happens - been waiting all day.  In the Javascript Console it shows: 

exportify.js:310 Uncaught TypeError: Cannot read property 'total' of null

If I export just 1 playlist it works but it does take a while.

**Comment by martenjacobs** [comment]
@shape55 You are right. I hadn't tested the "Export All"-button, but it runs into the same error as the playlist-list that some playlists seem to be unsupported. I created a fix where unsupported playlists are skipped. I created a new branch for this in my repo, so the url is different:
https://cdn.rawgit.com/martenjacobs/exportify/fixes/exportify.html

**Comment by shape55** [comment]
Ok, well the Export All button works now but after clicking it I get this error below, which is the same error I've always gotten with Exportify.  I figured this would have been fixed by now as I haven't tried it in about a year.

"Oops, Exportify has encountered a rate limiting error while using the Spotify API. This might be because of the number of users currently exporting playlists, or perhaps because you have too many playlists to export all at once. Try creating your own Spotify application. If that doesn't work, please add a comment to this issue where possible resolutions are being discussed.

It should still be possible to export individual playlists, particularly when using your own Spotify application."

I'm using Chrome.  When I try to export single playlists now it downloads them instantaneously. Nice to hear that it works that fast for 50 playlists too. I can test it with only 1 playlist though b/c of the error.

**Comment by martenjacobs** [comment]
@shape55 Rate limitations in the Spotify API are out of my hands of course. A possible solution would be to add a way to select multiple items from the list of playlists so you could at least download the playlists 50 at a time. However, at the moment I don't really have the time to further develop this project. I just wanted to fix the issue that made the project completely unusable for a number of users. Of course, I'm open to pull request on my fork of this repo.

**Comment by 7720** [comment]
Until recently I was able to print of my Plaist from Spotify which had been
automatically downloaded......Now it will only show my Ownership
number....(That has now gone)....and export all only shows me Zippid files
which when I open says EMPTY FILE ....MOST FRUSTRATING!!!

**Comment by shape55** [comment]
@martenjacobs - Ok, gotcha. Anyway, thanks for fixing it so it at least runs like it did previously.

Have you seen this app? a It looks like it's supposed to load more than 50 playlists.  At least it tries to, but it also recently stopped working. There are a lot of Issues posted with recent comments.

https://github.com/secuvera/SpotMyBackup

**Comment by jabalong** [comment]
@martenjacobs Thanks for the alternate link, it worked for me. Using Chrome in Windows 10 with a 5,000-track playlist and it downloaded right away.
