### ISSUE TITLE
Exportify 'Export All' not working

### ISSUE THREAD

**Issue by blueIndie** [watsonbox/exportify#56]
I use Exportify thankfully to back up a large number of playlists off Spotify so I need to use the 'Export All' option otherwise it's tedious and takes a long time to export singly.

When I hit the 'Export All' button nothing happens at all.

I use the latest version of Chrome (Also happens in Opera and Firefox) on Win 10.

Any ideas?

**Comment by ocram** [comment]
It seems that the fix from [this pull request](https://github.com/watsonbox/exportify/pull/44) may have to be applied in the `PlaylistsExporter` as well.

Until this is fixed, you can find a working version in [our fork](https://github.com/delight-im/exportify).

**Comment by sunscreem** [comment]
Hey @ocram - thank you .. works a treat :)

**Comment by shape55** [comment]
@ocram – Thanks, but unfortunately I'm still getting the "Oops, Exportify has encountered a rate limiting error while using the Spotify API..." notification.  I do have 469 playlists though.  Isn't there a way to get it to return more than 50 playlists?

The [SpotMyBackup app](http://www.spotmybackup.com/) loads all playlists but it's a bit buggy and when it does download it's a single json file that's illegible and doesn't contain the tracklist/playlist info the way the csv file does.  https://github.com/secuvera/SpotMyBackup

There's also https://www.tunemymusic.com/ which can export a lot more than 50 playlists.

On another note, there is 1 playlist out of 469 that won't download for some reason when using the single Export button, and I've tried using 3 different Exportify forks on both Firefox & Chrome.  It can't be b/c there's too many tracks since there is another playlist that has even more tracks that downloads fine.  I'm wondering if it's b/c of a spacial character.  It's the only playlist that has music notes in the title, but plenty of other playlists have different special characters.

**Comment by ocram** [comment]
@sunscreem Thanks for your appreciation!

@shape55 Thanks! If you encounter problems with rate limiting, the README suggests you should create your own Spotify API application and use the credentials from that application instead. If, after that, you still have problems, you may find [this issue](https://github.com/delight-im/exportify/issues/3) helpful. Finally, you can export all your 469 playlists one by one, which should work (but takes time, of course). As for the playlist that doesn’t export, you can either use the developer tools of your browser and find the problem with the JavaScript debugger, or you may share a playlist that doesn’t work so that somebody else can reproduce this.

**Comment by shape55** [comment]
Thanks – yes, I did see the note on creating your own Spotify API application before, but figured this required developer/coding knowledge, of which I have none.

The one by one export does work, but it takes forever and isn't practical, especially when there is no sortable column for "Last Updated" (or something to this effect), which would allow you to know the date each playlist was updated, therefore needing to export only the ones that have changed since your last backup.  This would be a very helpful feature, especially since the "Export All" function doesn't work for anyone with more than 50 playlists.  Making the existing columns sortable would be highly useful as well.

Regarding the sole playlist that I can't get to export, here are the links below if you want to see if it's reproducible on your end. Note, this is a playlist I subscribed to, not one that I created:
- Exportify playlist link: [spotify:playlist:53eljwwaQQhi93Zbet44si](url)
- Spotify URI: [spotify:user:reecerjd:playlist:53eljwwaQQhi93Zbet44si](url)

This is the error I get in the Firefox Browser Console after clicking the Export button for this playlist:

`TypeError: item.track is null exportify.html:339:13
    tracks https://rawgit.com/delight-im/exportify/master/exportify.html#access_token=BQDooptMSbHmO8oixsRcFhWPYvHVNY-esEo0adUvcu4PuwNzZUCFMg5a1do7ZnmQ4JBdV2nDgsBz4xleWykIKK8Vdm7OhwlY_lKakcdFEWibCtqXVNzh03hZRDzqQ1WW7kplLOdS_R7CPhwvwDkBVnNs_XRC5TTE60OJ&token_type=Bearer&expires_in=3600 line 184 > scriptElement:339
    map self-hosted:286
    tracks https://rawgit.com/delight-im/exportify/master/exportify.html#access_token=BQDooptMSbHmO8oixsRcFhWPYvHVNY-esEo0adUvcu4PuwNzZUCFMg5a1do7ZnmQ4JBdV2nDgsBz4xleWykIKK8Vdm7OhwlY_lKakcdFEWibCtqXVNzh03hZRDzqQ1WW7kplLOdS_R7CPhwvwDkBVnNs_XRC5TTE60OJ&token_type=Bearer&expires_in=3600 line 184 > scriptElement:337
    map self-hosted:286
    csvData https://rawgit.com/delight-im/exportify/master/exportify.html#access_token=BQDooptMSbHmO8oixsRcFhWPYvHVNY-esEo0adUvcu4PuwNzZUCFMg5a1do7ZnmQ4JBdV2nDgsBz4xleWykIKK8Vdm7OhwlY_lKakcdFEWibCtqXVNzh03hZRDzqQ1WW7kplLOdS_R7CPhwvwDkBVnNs_XRC5TTE60OJ&token_type=Bearer&expires_in=3600 line 184 > scriptElement:336
    jQuery 8
        then
        j
        fireWith
        h
        j
        fireWith
        x
        b
`

**Comment by shape55** [comment]
Regarding the playlist I was following that wouldn't export, the bug was identified [here](https://github.com/pavelkomarov/exportify/issues/10) using Pavel Komarov's fork of Exportify. He figured out what was causing it and made some improvements to the Export All function.

Also, see his comments [here](https://github.com/watsonbox/exportify/issues/6#issuecomment-508098381) about rate-limiting and using your own clientid.

**Comment by pavelkomarov** [comment]
Yes, my version has working Export All functionality.

[exportify.net](https://exportify.net)

**Comment by watsonbox** [comment]
I'll look at the rate limiting topic in https://github.com/watsonbox/exportify/issues/12 and the export bug in https://github.com/watsonbox/exportify/issues/48. Thanks for the comments and sorry for the delay.

**Comment by shape55** [comment]
Is Export All supposed to work now?  How many playlists has it been tested with?  I tried it several times w/ 471 and I can't get it to complete the export.  I don't see any error messages though – it seems to just reload the page by itself and I have to click the "Get Started" button again to retry.

**Comment by watsonbox** [comment]
Hi, thanks for the info!

I've tested it myself on ~100 playlists but rely on reports like these to spot problems for larger amounts. Before assuming it's the rate limiting I'd be interested in any more information you might have that could help me to debug, for example:

* Are you using any of the "extra data" toggles? If you un-toggle them, does it work?
* How long does the export run for before failing? Does it always fail in the same place? (roughly according to progress bar)
* If you open up [Chrome Developer Tools](https://developers.google.com/web/tools/chrome-devtools) or equivalent in your browser, do you see any errors?

With such a large number of playlists, there's more chance of hitting a bug that's caused by some relatively rare issue with one of those playlists. Of course it's entirely possible that it's a rate limiting issue, but the way it's implemented (listening for and obeying wait signals from the server) doesn't seem especially likely to work better for smaller quantities of data than larger.
