### ISSUE TITLE
Can't log in to Spotify anymore after using this tool.

### ISSUE THREAD

**Issue by MartinNiederl** [watsonbox/exportify#83]
I was just listening to music via Spotify while using this tool and suddenly no more song was playing and all pages were empty.

Then I logged out and wanted to log in again and since then I get the following error message in the browser:

![image](https://user-images.githubusercontent.com/22956128/100435078-b46d6900-309d-11eb-9133-7e3d881cb38a.png)

In the desktop app I get the following error:

![image](https://user-images.githubusercontent.com/22956128/100435470-45444480-309e-11eb-8ba1-780fe047b355.png)

I never had any problems with Spotify before, but it seems that by logging in via the tool a maximum of allowed logins was reached, which I cannot undo.

Do you have any idea what I can do now?

**Comment by watsonbox** [comment]
That's extremely odd - I can't see how it could be related to usage of this tool since a) I've not come across any similar reports from users, and b) I'm using it non-stop for hours sometimes during development so if anyone was going to max out any usage quotas you'd have thought it would be me!

It's also worth noting that authorizing a third party app to access your data via the API is not the same as "logging in", although of course you do need to log in in order to do that. Of course anything is possible but I can't really see how this type of issue could arise as a consequence of using this tool.

Incidentally, are you using the Spotify web app? Perhaps this is some rare case related to that 🤷‍♂️ .

Did the issue resolve itself? If not I suggest contacting Spotify support.

**Comment by MartinNiederl** [comment]
Strangely enough, it worked again about one day later, which means I was able to sign in again.
I know that this will not be directly due to exportify, after all I am logged in on several devices at the same time. But there must have been some correlation.

And no, I only use the desktop and mobile applications but I also used the web application for testing where the error occurs.

Thanks for the answer!
I don't know exactly what happened there, but since it's already resolved I'll close this issue now.
