### ISSUE TITLE
Encountered TypeError: features[i] is undefined.

### ISSUE THREAD

**Issue by SynclineFault** [watsonbox/exportify#87]
Hello

I've been trying to export my main playlist but it keeps coming up with "Couldn't export songs i like. Encountered TypeError: features[i] is undefined. Please let us know." I have used Exportify in the past and I have a successful spreadsheet from the 26/10/20 but between then and now it's just stopped working. Thank you for the help in advance.

**Comment by watsonbox** [comment]
Hi, it looks like you initially raised this issue with a screenshot, but have since removed it.

It's lucky you did because it was the screenshot that allowed me to notice that you're using a separate forked version of Exportify. I believe you're using the fork at https://github.com/pavel-aicradle/exportify which although is based on an older version of this repo is not at all associated with it.

I suggest that if you want to use that fork you raise your issues on the corresponding repo, otherwise feel free to retry with https://watsonbox.github.io/exportify/.

**Comment by SynclineFault** [comment]
Sorry mate, first time raising issues on this website, I didn't even realise I'd managed to do that. It's all working fine now, thank you for the help

**Comment by watsonbox** [comment]
That's quite alright, it's not especially clear I'm afraid. Glad you're up and running.
